name: FTP hash sync
description: Synchronizes files to a remote FTP or SFTP repository by using file hashes

inputs:
    protocol:
        description: Protocol, either "ftp" or "sftp"
        required: true

    host:
        description: Target host
        required: true

    username:
        description: Target username
        required: true

    password:
        description: Target password
        required: false
        default: ''

    source:
        description: source path, relative to repository root
        required: false
        default: .

    destination:
        description: destination path
        required: false
        default: .

    hashfile:
        description: hash filename
        required: false
        default: hashes.sha256

    hashtype:
        description: hash type
        required: false
        default: sha256

runs:
    using: docker
    image: Dockerfile

branding:
    icon: upload
    color: red
