name: FTP hash sync
description: Synchronizes files to a remote FTP or SFTP repository by using file hashes

inputs:
    protocol:
        description: protocol, either "ftp" or "sftp"
        required: true

    host:
        description: target host
        required: true

    username:
        description: target username
        required: true

    password:
        description: password (for FTP only)
        required: false
        default: ''

    clientkey:
        description: client SSH private key (for SFTP only)
        required: false

    hostkey:
        description: host SSH public key (for SFTP only)
        required: false

    source:
        description: source path, relative to repository root
        required: false
        default: .

    destination:
        description: destination path
        required: false
        default: .

    hashfile:
        description: hash filename
        required: false
        default: hashes.sha256

    hashtype:
        description: hash type
        required: false
        default: sha256

    retries:
        description: connection retries
        required: false
        default: 3

    timeout:
        description: connection timeout
        required: false
        default: 10

runs:
    using: docker
    image: Dockerfile

branding:
    icon: upload
    color: red
